export const jobMode = ["Remote", "On site", "Hybrid"];
export const experienceLevel = [
  "Internship",
  "Entry Level",
  "Associate",
  "Mid-Senior Level",
  "Senior Level",
  "Manager",
  "Director",
  "Executive",
];
export const jobType = [
  "Full-time",
  "Part-time",
  "Contract",
  "Temporary",
  "Internship",
  "Other",
];
export const category = [
  "All",
  "Blog",
  "Call Center",
  "Email Support",
  "eCommerce",
  "Growth Hacking",
  "Guides",
  "Information Technology",
  "Leads Generation",
  "Software Development",
  "Sales",
];
export const jobPostings = [
  {
    title: "Telecaller ",
    experience_level: experienceLevel[0],
    category: category[1],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[0],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Customer Support",
    experience_level: experienceLevel[1],
    category: category[2],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[1],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Customer Support",
    experience_level: experienceLevel[2],
    category: category[3],
    job_mode: jobMode[2],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[2],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Customer Support",
    experience_level: experienceLevel[3],
    category: category[4],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[3],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Customer Support",
    experience_level: experienceLevel[4],
    category: category[5],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[4],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[5],
    category: category[6],
    job_mode: jobMode[2],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[5],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[6],
    category: category[7],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[5],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[7],
    category: category[8],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[0],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Outside Sales Manager",
    experience_level: experienceLevel[1],
    category: category[9],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[1],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[2],
    category: category[10],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[2],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[0],
    category: category[1],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[3],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[1],
    category: category[2],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[4],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: " Customer Support",
    experience_level: experienceLevel[0],
    category: category[1],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[0],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: " Customer Support",
    experience_level: experienceLevel[1],
    category: category[2],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[1],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: " Customer Support",
    experience_level: experienceLevel[2],
    category: category[3],
    job_mode: jobMode[2],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[2],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: " Customer Support",
    experience_level: experienceLevel[3],
    category: category[4],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[3],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[4],
    category: category[5],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[4],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[5],
    category: category[6],
    job_mode: jobMode[2],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[5],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[6],
    category: category[7],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[5],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[7],
    category: category[8],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[0],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Telecaller ",
    experience_level: experienceLevel[1],
    category: category[9],
    job_mode: jobMode[0],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[1],
    salary_type: "Yearly",
    salary: 100000,
  },
  {
    title: "Customer Support",
    experience_level: experienceLevel[2],
    category: category[10],
    job_mode: jobMode[1],
    address: "Al Tawhidi Building, Dubai - UAE",
    employment: jobType[2],
    salary_type: "Yearly",
    salary: 100000,
  },
];
